version: "3.7"

services:
  postgres:
    image: postgres:alpine
    container_name: "my-db"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "default"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U admin -d default'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    image: my-api
    container_name: "my-api"
    environment:
      DB_HOST: "postgres" # SERVICE NAME ^
      DB_NAME: "default"
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      DB_PORT: "5432"
      API_PORT: "8080"
      API_MODE: "release"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db_data:
    name: go-api-pg-data
