version: "3.7"

services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27017:27017"
    command:
      - "--logpath"
      - "/var/log/mongodb/mongod.log"
      - "--quiet"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "venv"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
    volumes:
      - mongodb_data:/data/db

  api:
    build: .
    image: go-api
    container_name: "go-api"
    ports:
      - "8080:8080"
    environment:
      DB_CONNSTRING: "mongodb://venv:secret@mongodb:27017"
      API_PORT: "8080"
      API_MODE: "release"
    depends_on:
      - "mongodb"

volumes:
  mongodb_data:
    name: "mongodb_data"
